module "cognitive_account" {
  source   = "Azure/avm-res-cognitiveservices-account/azurerm"
  for_each = var.cognitive_accounts

  kind                                          = each.value.kind
  location                                      = each.value.location
  name                                          = each.value.name
  parent_id                                     = each.value.parent_id
  sku_name                                      = each.value.sku_name
  allow_project_management                      = each.value.allow_project_management
  aml_workspace                                 = each.value.aml_workspace
  associated_projects                           = each.value.associated_projects
  cognitive_deployments                         = coalesce(each.value.cognitive_deployments, {})
  custom_question_answering_search_service_id   = each.value.custom_question_answering_search_service_id
  custom_question_answering_search_service_key  = each.value.custom_question_answering_search_service_key
  custom_subdomain_name                         = each.value.custom_subdomain_name
  customer_managed_key                          = each.value.customer_managed_key
  default_project                               = each.value.default_project
  deployment_serialization_enabled              = each.value.deployment_serialization_enabled
  diagnostic_settings                           = coalesce(each.value.diagnostic_settings, {})
  dynamic_throttling_enabled                    = each.value.dynamic_throttling_enabled
  enable_telemetry                              = each.value.enable_telemetry
  fqdns                                         = each.value.fqdns
  is_hsm_key                                    = each.value.is_hsm_key
  local_auth_enabled                            = each.value.local_auth_enabled
  lock                                          = each.value.lock
  managed_identities                            = each.value.managed_identities
  network_acls                                  = each.value.network_acls
  outbound_network_access_restricted            = each.value.outbound_network_access_restricted
  private_endpoints                             = coalesce(each.value.private_endpoints, {})
  private_endpoints_manage_dns_zone_group       = each.value.private_endpoints_manage_dns_zone_group
  public_network_access_enabled                 = each.value.public_network_access_enabled
  qna_runtime_endpoint                          = each.value.qna_runtime_endpoint
  rai_monitor_config                            = each.value.rai_monitor_config
  rai_policies                                  = coalesce(each.value.rai_policies, {})
  role_assignments                              = coalesce(each.value.role_assignments, {})
  storage                                       = each.value.storage
  tags                                          = each.value.tags
  timeouts                                      = each.value.timeouts
}
